name: Continuous Integration

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    secrets: inherit
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-node-lint.yml@main

  test:
    secrets: inherit
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-node-tests.yml@main
    needs: lint

  build:
    secrets: inherit
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-node-build.yml@main
    needs: test

  scan:
    secrets: inherit
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-scan.yml@main
    needs: build
