name: Continuous Integration

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  lint:
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-node-lint.yml@main
    with:
      node-version: "12"
  build:
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-node-build.yml@main
    with:
      node-version: "12"
    needs:
      - lint
  push-scan:
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-push-scan-image.yml@main
    secrets: inherit
    needs:
      - build
